"""initial schema

Revision ID: 0001_initial
Revises: 
Create Date: 2026-07-04 11:46:56.798181
"""
from alembic import op
import sqlalchemy as sa


revision = '0001_initial'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('depots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('eroeffnet_am', sa.Date(), nullable=False),
    sa.Column('basiswaehrung', sa.String(length=3), nullable=False),
    sa.Column('notiz', sa.Text(), nullable=True),
    sa.Column('angelegt_am', sa.DateTime(), nullable=False),
    sa.Column('default_zeitraum', sa.String(length=30), nullable=False),
    sa.Column('default_bezugsbasis', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('instrumente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('isin', sa.String(length=12), nullable=False),
    sa.Column('wkn', sa.String(length=10), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('kategorie', sa.String(length=30), nullable=False),
    sa.Column('waehrung', sa.String(length=3), nullable=False),
    sa.Column('referenzboerse', sa.String(length=50), nullable=True),
    sa.Column('symbol', sa.String(length=50), nullable=True),
    sa.Column('basiswert', sa.String(length=200), nullable=True),
    sa.Column('angelegt_am', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('isin')
    )
    op.create_table('kurs_einstellungen',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kursgruppe', sa.String(length=30), nullable=False),
    sa.Column('provider_name', sa.String(length=50), nullable=False),
    sa.Column('credentials_verschluesselt', sa.Text(), nullable=True),
    sa.Column('abfrage_intervall_sekunden', sa.Integer(), nullable=False),
    sa.Column('aktiv', sa.Boolean(), nullable=False),
    sa.Column('geaendert_am', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kursgruppe')
    )
    op.create_table('waehrungs_einstellungen',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_name', sa.String(length=50), nullable=False),
    sa.Column('credentials_verschluesselt', sa.Text(), nullable=True),
    sa.Column('abfrage_intervall_sekunden', sa.Integer(), nullable=False),
    sa.Column('aktiv', sa.Boolean(), nullable=False),
    sa.Column('geaendert_am', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wechselkurse',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('von', sa.String(length=3), nullable=False),
    sa.Column('nach', sa.String(length=3), nullable=False),
    sa.Column('datum', sa.Date(), nullable=False),
    sa.Column('kurs', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('zeitstempel', sa.DateTime(), nullable=False),
    sa.Column('quelle', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('von', 'nach', 'datum')
    )
    op.create_table('depot_bewertungen',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('depot_id', sa.Integer(), nullable=False),
    sa.Column('datum', sa.Date(), nullable=False),
    sa.Column('depotbestand', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('barbestand', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('gesamtwert', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.ForeignKeyConstraint(['depot_id'], ['depots.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('depot_id', 'datum')
    )
    op.create_index(op.f('ix_depot_bewertungen_depot_id'), 'depot_bewertungen', ['depot_id'], unique=False)
    op.create_table('depot_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('depot_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('erstellt_am', sa.DateTime(), nullable=False),
    sa.Column('notiz', sa.Text(), nullable=True),
    sa.Column('depotbestand', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('barbestand', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('gesamtwert', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('realisierter_gewinn', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('unrealisierter_gewinn', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('dividenden', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('steuern', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('gesamtgewinn', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('gesamtergebnis', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('positionen_json', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['depot_id'], ['depots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_depot_snapshots_depot_id'), 'depot_snapshots', ['depot_id'], unique=False)
    op.create_table('dividenden',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('depot_id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('betrag', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('zeitpunkt', sa.DateTime(), nullable=False),
    sa.Column('notiz', sa.Text(), nullable=True),
    sa.Column('betrag_je_anteil', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('stueck_zum_zeitpunkt', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('angelegt_am', sa.DateTime(), nullable=False),
    sa.Column('geaendert_am', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['depot_id'], ['depots.id'], ),
    sa.ForeignKeyConstraint(['instrument_id'], ['instrumente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dividenden_depot_id'), 'dividenden', ['depot_id'], unique=False)
    op.create_index(op.f('ix_dividenden_instrument_id'), 'dividenden', ['instrument_id'], unique=False)
    op.create_table('kaeufe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('depot_id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('stueck', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('kaufkurs', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('kauf_zeitpunkt', sa.DateTime(), nullable=False),
    sa.Column('spesen', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('boerse', sa.String(length=50), nullable=True),
    sa.Column('angelegt_am', sa.DateTime(), nullable=False),
    sa.Column('geaendert_am', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['depot_id'], ['depots.id'], ),
    sa.ForeignKeyConstraint(['instrument_id'], ['instrumente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kaeufe_depot_id'), 'kaeufe', ['depot_id'], unique=False)
    op.create_index(op.f('ix_kaeufe_instrument_id'), 'kaeufe', ['instrument_id'], unique=False)
    op.create_table('kurse',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('kurs', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('waehrung', sa.String(length=3), nullable=False),
    sa.Column('boerse', sa.String(length=50), nullable=True),
    sa.Column('zeitstempel', sa.DateTime(), nullable=False),
    sa.Column('quelle', sa.String(length=20), nullable=False),
    sa.Column('vortagesschluss', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.ForeignKeyConstraint(['instrument_id'], ['instrumente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kurse_instrument_id'), 'kurse', ['instrument_id'], unique=False)
    op.create_index(op.f('ix_kurse_zeitstempel'), 'kurse', ['zeitstempel'], unique=False)
    op.create_table('schlusskurse',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('datum', sa.Date(), nullable=False),
    sa.Column('schlusskurs', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('quelle', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instrumente.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instrument_id', 'datum')
    )
    op.create_index(op.f('ix_schlusskurse_instrument_id'), 'schlusskurse', ['instrument_id'], unique=False)
    op.create_table('steuerverrechnungen',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('depot_id', sa.Integer(), nullable=False),
    sa.Column('betrag', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('zeitpunkt', sa.DateTime(), nullable=False),
    sa.Column('notiz', sa.Text(), nullable=True),
    sa.Column('angelegt_am', sa.DateTime(), nullable=False),
    sa.Column('geaendert_am', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['depot_id'], ['depots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_steuerverrechnungen_depot_id'), 'steuerverrechnungen', ['depot_id'], unique=False)
    op.create_table('verkaeufe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('depot_id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('stueck', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('verkaufskurs', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('verkauf_zeitpunkt', sa.DateTime(), nullable=False),
    sa.Column('spesen', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('steuer', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('boerse', sa.String(length=50), nullable=True),
    sa.Column('realisierter_gewinn', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('angelegt_am', sa.DateTime(), nullable=False),
    sa.Column('geaendert_am', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['depot_id'], ['depots.id'], ),
    sa.ForeignKeyConstraint(['instrument_id'], ['instrumente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verkaeufe_depot_id'), 'verkaeufe', ['depot_id'], unique=False)
    op.create_index(op.f('ix_verkaeufe_instrument_id'), 'verkaeufe', ['instrument_id'], unique=False)
    op.create_table('zahlungen',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('depot_id', sa.Integer(), nullable=False),
    sa.Column('typ', sa.String(length=20), nullable=False),
    sa.Column('betrag', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('zeitpunkt', sa.DateTime(), nullable=False),
    sa.Column('notiz', sa.Text(), nullable=True),
    sa.Column('angelegt_am', sa.DateTime(), nullable=False),
    sa.Column('geaendert_am', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['depot_id'], ['depots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zahlungen_depot_id'), 'zahlungen', ['depot_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_zahlungen_depot_id'), table_name='zahlungen')
    op.drop_table('zahlungen')
    op.drop_index(op.f('ix_verkaeufe_instrument_id'), table_name='verkaeufe')
    op.drop_index(op.f('ix_verkaeufe_depot_id'), table_name='verkaeufe')
    op.drop_table('verkaeufe')
    op.drop_index(op.f('ix_steuerverrechnungen_depot_id'), table_name='steuerverrechnungen')
    op.drop_table('steuerverrechnungen')
    op.drop_index(op.f('ix_schlusskurse_instrument_id'), table_name='schlusskurse')
    op.drop_table('schlusskurse')
    op.drop_index(op.f('ix_kurse_zeitstempel'), table_name='kurse')
    op.drop_index(op.f('ix_kurse_instrument_id'), table_name='kurse')
    op.drop_table('kurse')
    op.drop_index(op.f('ix_kaeufe_instrument_id'), table_name='kaeufe')
    op.drop_index(op.f('ix_kaeufe_depot_id'), table_name='kaeufe')
    op.drop_table('kaeufe')
    op.drop_index(op.f('ix_dividenden_instrument_id'), table_name='dividenden')
    op.drop_index(op.f('ix_dividenden_depot_id'), table_name='dividenden')
    op.drop_table('dividenden')
    op.drop_index(op.f('ix_depot_snapshots_depot_id'), table_name='depot_snapshots')
    op.drop_table('depot_snapshots')
    op.drop_index(op.f('ix_depot_bewertungen_depot_id'), table_name='depot_bewertungen')
    op.drop_table('depot_bewertungen')
    op.drop_table('wechselkurse')
    op.drop_table('waehrungs_einstellungen')
    op.drop_table('kurs_einstellungen')
    op.drop_table('instrumente')
    op.drop_table('depots')
    # ### end Alembic commands ###
