"""Repository interfaces (persistence core). Implemented by
`infrastructure/persistence/sqlalchemy_repos.py`; services only depend on
these protocols, never on SQL.
"""
from __future__ import annotations

from datetime import date, datetime
from typing import Protocol, Sequence

from domain.entities import (
    Depot,
    DepotBewertung,
    DepotSnapshot,
    Dividende,
    Instrument,
    Kauf,
    Kurs,
    KursEinstellung,
    Schlusskurs,
    Steuerverrechnung,
    Verkauf,
    WaehrungsEinstellung,
    Wechselkurs,
    Zahlung,
)


class DepotRepository(Protocol):
    def list_all(self) -> Sequence[Depot]: ...
    def get(self, depot_id: int) -> Depot | None: ...
    def get_by_name(self, name: str) -> Depot | None: ...
    def add(self, depot: Depot) -> Depot: ...
    def delete(self, depot: Depot) -> None: ...


class InstrumentRepository(Protocol):
    def list_all(self) -> Sequence[Instrument]: ...
    def get(self, instrument_id: int) -> Instrument | None: ...
    def get_by_isin(self, isin: str) -> Instrument | None: ...
    def search(self, begriff: str) -> Sequence[Instrument]: ...
    def add(self, instrument: Instrument) -> Instrument: ...
    def list_in_depot(self, depot_id: int) -> Sequence[Instrument]: ...


class KaufRepository(Protocol):
    def get(self, kauf_id: int) -> Kauf | None: ...
    def list_for_depot(self, depot_id: int) -> Sequence[Kauf]: ...
    def list_for_position(self, depot_id: int, instrument_id: int) -> Sequence[Kauf]: ...
    def add(self, kauf: Kauf) -> Kauf: ...
    def delete(self, kauf: Kauf) -> None: ...


class VerkaufRepository(Protocol):
    def get(self, verkauf_id: int) -> Verkauf | None: ...
    def list_for_depot(self, depot_id: int) -> Sequence[Verkauf]: ...
    def list_for_position(self, depot_id: int, instrument_id: int) -> Sequence[Verkauf]: ...
    def add(self, verkauf: Verkauf) -> Verkauf: ...
    def delete(self, verkauf: Verkauf) -> None: ...


class ZahlungRepository(Protocol):
    def get(self, zahlung_id: int) -> Zahlung | None: ...
    def list_for_depot(self, depot_id: int) -> Sequence[Zahlung]: ...
    def add(self, zahlung: Zahlung) -> Zahlung: ...
    def delete(self, zahlung: Zahlung) -> None: ...


class DividendeRepository(Protocol):
    def get(self, dividende_id: int) -> Dividende | None: ...
    def list_for_depot(self, depot_id: int) -> Sequence[Dividende]: ...
    def add(self, dividende: Dividende) -> Dividende: ...
    def delete(self, dividende: Dividende) -> None: ...


class SteuerverrechnungRepository(Protocol):
    def get(self, id_: int) -> Steuerverrechnung | None: ...
    def list_for_depot(self, depot_id: int) -> Sequence[Steuerverrechnung]: ...
    def add(self, sv: Steuerverrechnung) -> Steuerverrechnung: ...
    def delete(self, sv: Steuerverrechnung) -> None: ...


class KursRepository(Protocol):
    def latest(self, instrument_id: int) -> Kurs | None: ...
    def add(self, kurs: Kurs) -> Kurs: ...
    def history(self, instrument_id: int, ab: datetime) -> Sequence[Kurs]: ...


class SchlusskursRepository(Protocol):
    def get(self, instrument_id: int, datum: date) -> Schlusskurs | None: ...
    def upsert(self, instrument_id: int, datum: date, kurs, quelle: str) -> Schlusskurs: ...
    def series(self, instrument_id: int, ab: date, bis: date | None = None) -> Sequence[Schlusskurs]: ...
    def latest_before(self, instrument_id: int, datum: date) -> Schlusskurs | None: ...


class DepotBewertungRepository(Protocol):
    def series(self, depot_id: int, ab: date | None = None, bis: date | None = None) -> Sequence[DepotBewertung]: ...
    def upsert(self, depot_id: int, datum: date, depotbestand, barbestand, gesamtwert) -> DepotBewertung: ...
    def delete_from(self, depot_id: int, ab: date) -> None: ...


class SnapshotRepository(Protocol):
    def get(self, snapshot_id: int) -> DepotSnapshot | None: ...
    def list_for_depot(self, depot_id: int) -> Sequence[DepotSnapshot]: ...
    def add(self, snapshot: DepotSnapshot) -> DepotSnapshot: ...
    def delete(self, snapshot: DepotSnapshot) -> None: ...


class KursEinstellungRepository(Protocol):
    def get_for_gruppe(self, kursgruppe: str) -> KursEinstellung | None: ...
    def list_all(self) -> Sequence[KursEinstellung]: ...
    def add(self, einstellung: KursEinstellung) -> KursEinstellung: ...


class WaehrungsEinstellungRepository(Protocol):
    def get_single(self) -> WaehrungsEinstellung | None: ...
    def add(self, einstellung: WaehrungsEinstellung) -> WaehrungsEinstellung: ...


class WechselkursRepository(Protocol):
    def latest(self, von: str, nach: str) -> Wechselkurs | None: ...
    def get_am(self, von: str, nach: str, datum: date) -> Wechselkurs | None: ...
    def latest_before(self, von: str, nach: str, datum: date) -> Wechselkurs | None: ...
    def upsert(self, von: str, nach: str, datum: date, kurs, quelle: str) -> Wechselkurs: ...
